server:
  port: 3004
spring:
  application:
    name: auth
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848       #注册到Nacos
  redis:
    host: 127.0.0.1   #redis的ip
    port: 6379        #
    password:
    pool:
      max-active: 100 #redis最大连接数，负数代表没有限制
      max-wait: -1    #redis阻塞等待时间，负数代表没有限制
      max-idle: 10    #redis最大空闲链接
      min-idle: 0     #redis最小空闲链接
    timeout: 2000     #redis超时时间，毫秒
logging:
  config: classpath:./log/logging.xml
logValue:
  consoleLevel: info